### PR TITLE
Selectmenu: remove selectmenu-icon-space and add selectmenu-icon

### PR DESCRIPTION
**Pull request by arschmitz**
Ref #14914
Ref gh-1671

### CODE REVIEW

**Comment by jzaefferer** [comment]
Looks good.

**Comment by arschmitz** [comment]
Closed by 61bb1cd

**Comment by AurelioDeRosa** [comment]
Quick note @arschmitz. Can you fix in the links in your first message (and perhaps in the commit message)? Thank you

**Comment by scottgonzalez** [comment]
The references are correct.

**Comment by AurelioDeRosa** [comment]
No doubts on that. They are just non clickable. I should have been more clear on what I meant.

**Pull request closed without merging**
