### PR TITLE
Effects: Clean up queue wording since we don't support jQuery <1.7

### PR DESCRIPTION
**Pull request by scottgonzalez**
Fixes gh-141

So sad that I couldn't put a description inside each type. That gets me every time. :-(

### CODE REVIEW

**Comment by arthurvr** [comment]
LGTM! :+1:

**Comment by jzaefferer** [comment]
:+1:

**Comment by scottgonzalez** [comment]
Merged into 1-12.

**Comment by jzaefferer** [comment]
> So sad that I couldn't put a description inside each type. That gets me every time. :-(

We have `<desc>` elements inside `<type>` elsewhere, e.g. `entry/options/option`. Not supported inside `<property>`?

**Comment by scottgonzalez** [comment]
Nope. I believe it's limited to widget options. This is what happens when someone who has never written XSL is put in charge of writing all the new XSL to support our API sites :unamused: I'd really like to refactor the whole thing and document it, but that's fairly time consuming. I think it'd be worth it though.

**Pull request closed without merging**
