### PR TITLE
Datepicker: Add documentation for onUpdateDatepicker callback option

### PR DESCRIPTION
**Pull request by patrick-vandy**
Update datepicker's documentation for changes made in https://github.com/jquery/jquery-ui/pull/1912

### CODE REVIEW

**Review by fnagel — APPROVED** [review]

**Review by mgol — APPROVED** [review]

**Comment by mgol** [comment]
The change looks good, thanks!

@fnagel are you familiar with how the docs for a specific version are generated? I wonder if updating the `main` branch wouldn't update the 1.12 docs. If that's the case then we need to prepare a 1.13 setup before merging this, let's keep this in mind.

**Comment by fnagel** [comment]
@mgol No, I'm not familiar, but you're right, we should keep this in mind. Did you create a checklist somewhere?

**Comment by mgol** [comment]
I was thinking about doing the API setup for 1.13 before merging this but we can't as the main URLs like https://api.jqueryui.com/addClass/ need to resolve to 1.12 as long as 1.13 is not released yet. This is good to merge then, we just need to not tag commits on `main` before the 1.13 release; if any 1.12 docs need updates, we can create tags on the `1-12` branch.

I'll merge the PR.

**Comment by mgol** [comment]
Landed, thanks for the docs update, @patrick-vandy!

**Pull request merged**
