### PR TITLE
Menu: Document the new wrapper requirement

### PR DESCRIPTION
**Pull request by tjvantoll**
Fixes gh-234

### CODE REVIEW

**Comment by jzaefferer** [comment]
@scottgonzalez can you take (another) look at this? Should be good to land as well.

**Comment by scottgonzalez** [comment]
Looks good.

**Comment by jzaefferer** [comment]
Just merged, but GitHub doesn't close this PR: https://github.com/jquery/api.jqueryui.com/commit/dd2629fea0f643d846e12604d4941f5e81bea05a

What am I missing?

**Comment by scottgonzalez** [comment]
Commits to branches don't close issues or PRs.

**Comment by jzaefferer** [comment]
Right, I guess it worked for #243 because it was a merge.

**Pull request closed without merging**
