### PR TITLE
datePicker: add currentText to the existing description

### PR DESCRIPTION
**Pull request by gauravcool**
Fixes gh-273

### CODE REVIEW

**Comment by arthurvr** [comment]
@kborchers Did you notice the missing CLA signature? The name on the commit was invalid.

**Comment by kborchers** [comment]
Yes I noticed. I was teaching a workshop and wanted him to get his commit merged after the nightmare experience we currently provide for Windows users trying to contribute to our websites. Let me know the best way forward to correct this and I can work on fixing it.

**Comment by arschmitz** [comment]
There are several things wrong with this commit, none of them can be fixed properly at this point without re-writing history. At this point we would either need to force push the repo to change the commit name and message, or we will have to add a mailmap to the repo and ignore the other issues. Sadly I think a mailmap and ignoring the commit message issues is realistically the only option now. The CLA checker was created specifically to stop this type of commit and takes only seconds to run and updates every 60 seconds re checking invalid signatures.

Maybe next time use this as a teaching opportunity to show how to rebase and amend a commit, rather then pushing without due process out of frustration.

Also if you ran into problems contributing on Windows could you please open issues for these. I didn't see any new issues.

**Comment by arthurvr** [comment]
Thanks for the detailed explanation, @arschmitz.

I'm at all not the right one to complain about things like this, but if the workshop covered how to contribute, getting the CLA signature and git config right should've been a part of it.

And yeah, sorry for the pain on Windows. Thus far I only saw a few people who got the setup working on windows. Though, as @arschmitz said, it's important to open issues so we can (try to) fix them...

@kborchers Side: I don't know if you've noticed, but this commit also had the same mistake as I pointed you at a few hours earlier in the Chassis ticket. It misses a [`Closes` statement](http://contribute.jquery.org/commits-and-pull-requests/#commit-guidelines) in the commit message, to make sure there's a reference to the PR on the commit.

**Pull request merged**
