### PR TITLE
change http to https where applicable

### PR DESCRIPTION
**Pull request by OmgImAlexis**
`https://xmlsoft.org/` has an incorrect SSL cert so I couldn't change that.
Sourceforge redirects https to http so I couldn't change that either.

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Please fix the whitespace.

**Comment by OmgImAlexis** [comment]
@scottgonzalez this repo also needs a editorconfig. Nothing I can really do with my editor until one is added as it'll auto convert the tabs to spaces on save unless there's an editorconfig.

I'll just wait for it to be added before fixing it in this repo and others I've got PRs open on.

**Comment by jzaefferer** [comment]
> I'll just wait for it to be added before fixing it in this repo and others I've got PRs open on.

Or add a copy of https://github.com/jquery/api.qunitjs.com/blob/master/.editorconfig to this repo.

**Comment by scottgonzalez** [comment]
Ok, I'll wait for the editorconfig update to land first, but you should really look into your editor's settings if you truly believe there's nothing you can do without a config file. Either your editor is severely limited (which I doubt), or there are settings you're just not aware of.

**Comment by OmgImAlexis** [comment]
It's not that, I'm using atom.io and I have a few hundred files I'm working on at the moment. Currently in OSX if you close ANY window all of them cause it to crash and editing the config will update all of my files. If I wait for the editorconfig to be added I won't have to manually save and close all of them just to change the settings.

**Pull request closed without merging**
